CC=gcc
CC+=-DDEBUG -g
CFLAGS=-c -Wall
LDFLAGS=
COMMON_SOURCES=EventReader.C EventReaderDict.C
COMMON_OBJECTS=$(COMMON_SOURCES:.C=.o)

MAIN1_SOURCES=main.C
MAIN1_OBJECTS=$(MAIN1_SOURCES:.C=.o)
EXECUTABLE1=AnalysisLSAlphas

MAIN2_SOURCES=main_lowE.C
MAIN2_OBJECTS=$(MAIN2_SOURCES:.C=.o)
EXECUTABLE2=AnalysisLSAlphas_lowE

CFLAGS += $(shell $(ROOTSYS)/bin/root-config --cflags)
LDFLAGS += $(shell $(ROOTSYS)/bin/root-config --libs) -lstdc++

CFLAGS += -I../ 

all: $(EXECUTABLE1) $(EXECUTABLE2)

$(EXECUTABLE1): $(MAIN1_OBJECTS) $(COMMON_OBJECTS)
	$(CC) $(LDFLAGS) $(MAIN1_OBJECTS) $(COMMON_OBJECTS) -o $@

$(EXECUTABLE2): $(MAIN2_OBJECTS) $(COMMON_OBJECTS)
	$(CC) $(LDFLAGS) $(MAIN2_OBJECTS) $(COMMON_OBJECTS) -o $@

.C.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -f *.o $(EXECUTABLE1) $(EXECUTABLE2)
